# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-probe" do
  version "0.0.3"

  on_macos do
    on_intel do
      url "https://github.com/xenos76/aws-probe/releases/download/#{version}/aws-probe_#{version}_Darwin_amd64.tar.gz"
      sha256 "6b8498abfc898224ff17fe9b5cf3f2297147caa84b088836b1b8125b3eda3b99"
    end
    on_arm do
      url "https://github.com/xenos76/aws-probe/releases/download/#{version}/aws-probe_#{version}_Darwin_arm64.tar.gz"
      sha256 "6efcc2f9f0c969ce2561c7f456e2175204ba4e8fb1d25ba123669de29fd58b7f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/xenos76/aws-probe/releases/download/#{version}/aws-probe_#{version}_Linux_amd64.tar.gz"
      sha256 "1cfc7c8807dfbfe19b95d08b318190aca04fc3e117090cf6232f1d06b8c7c619"
    end
    on_arm do
      url "https://github.com/xenos76/aws-probe/releases/download/#{version}/aws-probe_#{version}_Linux_arm64.tar.gz"
      sha256 "bb0b01e400f478b25d9727873f236aabc02be293c915778967a77980291714f6"
    end
  end

  name "aws-probe"
  desc "aws-probe, a tool for checking cloud wiring"
  homepage "https://github.com/xenOs76/aws-probe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-probe"

  # No zap stanza required

end
