# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-probe" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "050e3a1241f3c623ed8a8f9922a4c914895aca755e04e819972d0a2c88dc28c4"
      url "https://github.com/xenos76/aws-probe/releases/download/#{version}/aws-probe_#{version}_Darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "03e2c3dcc72636bb73ad72b8b5a73921a4041bbc8d347b8cb67745fc6093ee7e"
      url "https://github.com/xenos76/aws-probe/releases/download/#{version}/aws-probe_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cb840bd7d3fc2f19eb1bef72636ae83a630e69b3769e39c8a34ecd727632c57a"
      url "https://github.com/xenos76/aws-probe/releases/download/#{version}/aws-probe_#{version}_Linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0b03202b931dc234d6db8c37789ed520f086adbfddbb41ec865d1bfad448716e"
      url "https://github.com/xenos76/aws-probe/releases/download/#{version}/aws-probe_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "aws-probe"
  desc "aws-probe, a tool for checking cloud wiring"
  homepage "https://github.com/xenOs76/aws-probe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-probe"
  bash_completion "completions/aws-probe.bash"
  fish_completion "completions/aws-probe.fish"
  zsh_completion "completions/aws-probe.zsh"

  # No zap stanza required

end
