# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-probe" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "9b2873c6051f2d5907c42cbc8eb192fe61cee4754cd9b0f5108fe881ef991c68"
      url "https://github.com/xenos76/aws-probe/releases/download/#{version}/aws-probe_#{version}_Darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f4f1d288d8a09a6d3103583f5e7fafce59422ddf6be90e0b59210de14d8e1290"
      url "https://github.com/xenos76/aws-probe/releases/download/#{version}/aws-probe_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6eacafbe7c2bdac687ae30ac0d61af64da8d2bc07ce69f2217fab0387b3e1990"
      url "https://github.com/xenos76/aws-probe/releases/download/#{version}/aws-probe_#{version}_Linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4787b272140dda96b2c85148d5bb2895baa97a92f310fd3a88b9e7b4f7ff82bf"
      url "https://github.com/xenos76/aws-probe/releases/download/#{version}/aws-probe_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "aws-probe"
  desc "aws-probe, a tool for checking cloud wiring"
  homepage "https://github.com/xenOs76/aws-probe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-probe"

  # No zap stanza required

end
