# This file was generated by GoReleaser. DO NOT EDIT.
cask "https-wrench" do
  version "0.12.1"

  on_macos do
    on_intel do
      sha256 "e6bfbea9ae297e4b486fdcd6ce7c82f2cb054986c65748d9df90a635daa6cbd3"
      url "https://github.com/xenos76/https-wrench/releases/download/#{version}/https-wrench_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1ae87e13ac7942813cd688caf5e8bfb748b82572d38c06c4b88f93118eaa9560"
      url "https://github.com/xenos76/https-wrench/releases/download/#{version}/https-wrench_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ec75df4694e234cd07d32ad7ce3c2e28d6462295cec77aa695fd9293d128a9d1"
      url "https://github.com/xenos76/https-wrench/releases/download/#{version}/https-wrench_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e06a8ae0853d5986296305549c63e4c3c84316fbb29fb74fc73695d0d15f8b0a"
      url "https://github.com/xenos76/https-wrench/releases/download/#{version}/https-wrench_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "https-wrench"
  desc "https-wrench"
  homepage "https://github.com/xenOs76/https-wrench"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "https-wrench"
  manpage "manpages/https-wrench-certinfo.1.gz"
  manpage "manpages/https-wrench-requests.1.gz"
  manpage "manpages/https-wrench.1.gz"
  bash_completion "completions/https-wrench.bash"
  fish_completion "completions/https-wrench.fish"
  zsh_completion "completions/https-wrench.zsh"

  # No zap stanza required

end
