# This file was generated by GoReleaser. DO NOT EDIT.
cask "https-wrench" do
  name "https-wrench"
  desc "https-wrench"
  homepage "https://github.com/xenOs76/https-wrench"
  version "0.8.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "https-wrench"

  on_macos do
    on_intel do
      url "https://github.com/xenos76/https-wrench/releases/download/#{version}/https-wrench_#{version}_Darwin_x86_64.tar.gz"
      sha256 "445ddadd48bd5e61a11008d5d280197ac4440283db618f152420b165da6ea822"
    end
    on_arm do
      url "https://github.com/xenos76/https-wrench/releases/download/#{version}/https-wrench_#{version}_Darwin_arm64.tar.gz"
      sha256 "3f8a90adf8a60e3e5f5bc54f99b1a736a752b0ee98bde2ea0aa93cfbba869bb3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/xenos76/https-wrench/releases/download/#{version}/https-wrench_#{version}_Linux_x86_64.tar.gz"
      sha256 "9efa80bbc61ae41bdd562877f81849a805f43285a6b8ff8438c39146c174e4ed"
    end
    on_arm do
      url "https://github.com/xenos76/https-wrench/releases/download/#{version}/https-wrench_#{version}_Linux_arm64.tar.gz"
      sha256 "22324ea97397e675e7f0f46eeee728a65f171984135cbfb19dd95000c73f8b10"
    end
  end

  # No zap stanza required
end
