# This file was generated by GoReleaser. DO NOT EDIT.
cask "https-wrench" do
  name "https-wrench"
  desc "https-wrench"
  homepage "https://github.com/xenOs76/https-wrench"
  version "0.9.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "https-wrench"
  manpage "manpages/https-wrench-certinfo.1.gz"
  manpage "manpages/https-wrench-requests.1.gz"
  manpage "manpages/https-wrench.1.gz"
  bash_completion "completions/https-wrench.bash"
  zsh_completion "completions/https-wrench.zsh"
  fish_completion "completions/https-wrench.fish"

  on_macos do
    on_intel do
      url "https://github.com/xenos76/https-wrench/releases/download/#{version}/https-wrench_#{version}_Darwin_x86_64.tar.gz"
      sha256 "11c1b1b0bcd3ffd8d6d3483eb90ccf3e841a5b11508948c27b47648402651075"
    end
    on_arm do
      url "https://github.com/xenos76/https-wrench/releases/download/#{version}/https-wrench_#{version}_Darwin_arm64.tar.gz"
      sha256 "748b1d5810bec992b02ad505baf66dd9b710e7fed8e30d822be1365768ff9898"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/xenos76/https-wrench/releases/download/#{version}/https-wrench_#{version}_Linux_x86_64.tar.gz"
      sha256 "37d9c76bd4cfae01ad92398d685e0dd1b8dcf22e812b4784d52dbdd02012df39"
    end
    on_arm do
      url "https://github.com/xenos76/https-wrench/releases/download/#{version}/https-wrench_#{version}_Linux_arm64.tar.gz"
      sha256 "75b7cac6ac72deb3f47a0fb8a90545b2d5254f4fba96b36f0e32428e2355a6df"
    end
  end

  # No zap stanza required
end
