# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-crdlist" do
  name "kubectl-crdlist"
  desc "kubectl-crdlist, CRD visualization plugin for Kubernetes."
  homepage "https://github.com/xenOs76/kubectl-crdlist"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-crdlist"

  on_macos do
    on_intel do
      url "https://github.com/xenos76/kubectl-crdlist/releases/download/#{version}/kubectl-crdlist_#{version}_Darwin_amd64.tar.gz"
      sha256 "bf8ac731c9567eb734d43d2d19d75e93f8f50e8bc8dfedb089592aa046123b9f"
    end
    on_arm do
      url "https://github.com/xenos76/kubectl-crdlist/releases/download/#{version}/kubectl-crdlist_#{version}_Darwin_arm64.tar.gz"
      sha256 "a44afdba8913ca08a1bedf5fffb158620fc3ac3691cf9a6cbb9a30962b5ce923"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/xenos76/kubectl-crdlist/releases/download/#{version}/kubectl-crdlist_#{version}_Linux_amd64.tar.gz"
      sha256 "48a5b13a6d5b49523ebaf4394ec2629711917ef49e15ca8be4c3a8497a6d63de"
    end
    on_arm do
      url "https://github.com/xenos76/kubectl-crdlist/releases/download/#{version}/kubectl-crdlist_#{version}_Linux_arm64.tar.gz"
      sha256 "c0407120b949146d4c99e28083fb227fd4056f4668c3a93b20d3ace005cbedca"
    end
  end

  # No zap stanza required
end
