# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-netdrill" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "b7130521716c7bc978e2e314c60db1052c79c4371fa711f2a56db43deeb5318a"
      url "https://github.com/xenos76/kubectl-netdrill/releases/download/#{version}/kubectl-netdrill_#{version}_Darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4dd0546303e6cc7afc3e6da29a67df1213421a9ed7b3e07a2d0bda482ec87365"
      url "https://github.com/xenos76/kubectl-netdrill/releases/download/#{version}/kubectl-netdrill_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "18809ef7d6c30141cf9791a130bdae776239e7351fda240cb187e672e5db0f67"
      url "https://github.com/xenos76/kubectl-netdrill/releases/download/#{version}/kubectl-netdrill_#{version}_Linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a3e8361ae79113e36bcdcb0ffbae428a8823225eca722df751a5f660688728ac"
      url "https://github.com/xenos76/kubectl-netdrill/releases/download/#{version}/kubectl-netdrill_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "kubectl-netdrill"
  desc "kubectl-netdrill, a network troubleshooting plugin for Kubernetes."
  homepage "https://github.com/xenOs76/kubectl-netdrill"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-netdrill"
  manpage "manpages/kubectl-netdrill-debug.1.gz"
  manpage "manpages/kubectl-netdrill-deployment.1.gz"
  manpage "manpages/kubectl-netdrill-pod.1.gz"
  manpage "manpages/kubectl-netdrill-run.1.gz"
  manpage "manpages/kubectl-netdrill.1.gz"
  bash_completion "completions/kubectl-netdrill.bash"
  fish_completion "completions/kubectl-netdrill.fish"
  zsh_completion "completions/_kubectl-netdrill"

  # No zap stanza required

end
