# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-crdlist" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "85e05f6145130f3bf3ac407308f5ba2ccbce397ac0ec759e2bc032ec690c7061"
      url "https://github.com/xenos76/kubectl-crdlist/releases/download/#{version}/kubectl-crdlist_#{version}_Darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e23d392952813791e6f9f0cdaab9032fede42e99fcfe073ed56d29d24d607216"
      url "https://github.com/xenos76/kubectl-crdlist/releases/download/#{version}/kubectl-crdlist_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fd19ad5c0528ff78076441e41700c96158626452f815f60af335250360457222"
      url "https://github.com/xenos76/kubectl-crdlist/releases/download/#{version}/kubectl-crdlist_#{version}_Linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bf0d59861c553aa4842e7a2e2ee18ef75ac34f7a7021d569243b3b3c1c75312e"
      url "https://github.com/xenos76/kubectl-crdlist/releases/download/#{version}/kubectl-crdlist_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "kubectl-crdlist"
  desc "kubectl-crdlist, CRD visualization plugin for Kubernetes."
  homepage "https://github.com/xenOs76/kubectl-crdlist"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-crdlist"

  # No zap stanza required

end
