# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-crdlist" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "fca581aaf96376848d31d2cb3311cd07c7f3f757a133d5dd9341583612124867"
      url "https://github.com/xenos76/kubectl-crdlist/releases/download/#{version}/kubectl-crdlist_#{version}_Darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "640b4bbbe386fb9331f90dac3ce9b1ae3d1adc87ebc2fdc71efb97afcd36d8c6"
      url "https://github.com/xenos76/kubectl-crdlist/releases/download/#{version}/kubectl-crdlist_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "10acd081b65e7e9794f5ef713c27db5119c0e0e464d0167f38e88cb134dc0ddb"
      url "https://github.com/xenos76/kubectl-crdlist/releases/download/#{version}/kubectl-crdlist_#{version}_Linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ea9a242e1befdb2b298ee07352de2471f487a3472d9347357c3d490cb2cdb639"
      url "https://github.com/xenos76/kubectl-crdlist/releases/download/#{version}/kubectl-crdlist_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "kubectl-crdlist"
  desc "kubectl-crdlist, CRD visualization plugin for Kubernetes."
  homepage "https://github.com/xenOs76/kubectl-crdlist"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-crdlist"

  # No zap stanza required

end
