# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-netdrill" do
  version "0.2.4"

  on_macos do
    on_intel do
      sha256 "c8e3cda8982de256ad6e77567e69887a908703532b44dda1fb5cb4ee15751493"
      url "https://github.com/xenos76/kubectl-netdrill/releases/download/#{version}/kubectl-netdrill_#{version}_Darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f1fcf8be2e185441b637f9b17d67dd6337f6548ed8eb857851d4d83454664954"
      url "https://github.com/xenos76/kubectl-netdrill/releases/download/#{version}/kubectl-netdrill_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f6a398b1f7e8fcb400254174578c5fffcce2f4b7e7b7d9133095beaeb6eb80b7"
      url "https://github.com/xenos76/kubectl-netdrill/releases/download/#{version}/kubectl-netdrill_#{version}_Linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "daf085ced6a4a86c8dd1e52452637d75c47130c1ae7c068051bdfcaf312d74b5"
      url "https://github.com/xenos76/kubectl-netdrill/releases/download/#{version}/kubectl-netdrill_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "kubectl-netdrill"
  desc "kubectl-netdrill, a network troubleshooting plugin for Kubernetes."
  homepage "https://github.com/xenOs76/kubectl-netdrill"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-netdrill"
  manpage "manpages/kubectl-netdrill-debug.1.gz"
  manpage "manpages/kubectl-netdrill-deployment.1.gz"
  manpage "manpages/kubectl-netdrill-pod.1.gz"
  manpage "manpages/kubectl-netdrill-run.1.gz"
  manpage "manpages/kubectl-netdrill.1.gz"
  bash_completion "completions/kubectl-netdrill.bash"
  fish_completion "completions/kubectl-netdrill.fish"
  zsh_completion "completions/_kubectl-netdrill"

  # No zap stanza required

end
